// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikjshkvjhitbdwzutpsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlranNoa3ZqaGl0YmR3enV0cHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjY1NjIsImV4cCI6MjA2NTc0MjU2Mn0.paRPUpAgAPvRknRivqHlhvh7QVrRMWs32R93dx30Kbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);